//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstelaVidaShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        public int ID { get; set; }
        public Nullable<int> Worker { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<byte> Month { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual Month Month1 { get; set; }
        public virtual Worker Worker1 { get; set; }
    }
}
