//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstelaVidaShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poluchenie_kredita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poluchenie_kredita()
        {
            this.Vyplata_kredita = new HashSet<Vyplata_kredita>();
        }
    
        public int ID { get; set; }
        public string Bank { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public Nullable<decimal> Procent { get; set; }
        public Nullable<decimal> Penya { get; set; }
        public Nullable<int> Let { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Ostatok { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vyplata_kredita> Vyplata_kredita { get; set; }
    }
}
