//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstelaVidaShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vyplata_kredita
    {
        public int ID { get; set; }
        public Nullable<int> Kredit { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public Nullable<decimal> Procent { get; set; }
        public Nullable<decimal> Penya { get; set; }
        public Nullable<decimal> Ostatok { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Sum_all { get; set; }
    
        public virtual Poluchenie_kredita Poluchenie_kredita { get; set; }
    }
}
